pipeline {
    agent any
    environment {
        PATH = "/usr/local/share/dotnet:$PATH" // .NET Core'un yüklü olduğu yolu güncelleyin
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Setup .NET Core') {
            steps {
                sh 'dotnet --version'
            }
        }
        stage('Build with dotnet') {
            steps {
                sh 'dotnet build --configuration Release'
            }
        }
        stage('Publish with dotnet') {
            steps {
                sh 'dotnet publish --configuration Release --output ./publish'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('', 'dockerhub_credentials') {
                        // Docker Hub işlemleri burada
                    }
                }
            }
        }
        stage('Build and Push Docker Image') {
            steps {
                sh '''
                docker build -t aysegulakbaas/samplewebapiaspnetcore:latest --target runtime .
                docker push aysegulakbaas/samplewebapiaspnetcore:latest
                '''
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                kubectl apply -f SampleWebApiAspNetCore/Deployment/deployment.yaml
                kubectl apply -f SampleWebApiAspNetCore/Deployment/ingress.yaml
                kubectl apply -f SampleWebApiAspNetCore/Deployment/service.yaml
                '''
            }
        }
    }
}
