apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-web-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: aysegul-sample-web-api-morgul-duman.com
    http:
      paths:
      - path: /api/v1/foods
        pathType: Prefix
        backend:
          service:
            name: sample-web-api-service  # Servis adı burada olmalı
            port:
              number: 80
