name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

  test:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Test with dotnet
      run: dotnet test --configuration Release

  deploy:
    runs-on: self-hosted
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        set -eux
        IMAGE_TAG=latest
        echo "Building and pushing image with tag $IMAGE_TAG"
        cd SampleWebApiAspNetCore
        docker build -t aysegulakbaas/samplewebapiaspnetcore:latest --target runtime .
        docker push aysegulakbaas/samplewebapiaspnetcore:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f SampleWebApiAspNetCore/Deployment/deployment.yaml
        kubectl apply -f SampleWebApiAspNetCore/Deployment/ingress.yaml
        kubectl apply -f SampleWebApiAspNetCore/Deployment/service.yaml
