name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output ./publish

    - name: Build Docker image
      run: |
        cd /Users/aysegul/Documents/github/Devops-ASPNETCore-WebAPI-Sample/SampleWebApiAspNetCore
        docker build -t aysegulakbaas/samplewebapiaspnetcore:latest .
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      run: |
        set -eux
        IMAGE_TAG=latest
        echo "Building and pushing image with tag $IMAGE_TAG"
        echo `pwd && ls`
        docker build -t aysegulakbaas/samplewebapiaspnetcore:latest --target stage-2 .
        docker image tag aysegulakbaas/samplewebapiaspnetcore:latest:$IMAGE_TAG
        docker images
        docker push aysegulakbaas/samplewebapiaspnetcore:latest:$IMAGE_TAG
    
   
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./Deployment/deployment.yaml
        kubectl apply -f ./Deployment/ingress.yaml
        kubectl apply -f ./Deployment/service.yaml
     
