name: .NET Core CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output ./publish

    - name: Build Docker image
      run: |
        cd /Users/aysegul/Documents/github/Devops-ASPNETCore-WebAPI-Sample/SampleWebApiAspNetCore
        docker build -t aysegulakbaas/s
